# Generated by Django 5.1.8 on 2026-06-28 17:04

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم رباعي')),
                ('phone_numbers', models.CharField(max_length=100, verbose_name='أرقام الهواتف')),
                ('account_type', models.CharField(choices=[('seller', 'بائع (صاحب عقار)'), ('buyer', 'مشتري (باحث عن عقار)')], default='buyer', max_length=10, verbose_name='نوع الحساب')),
                ('profile_picture', models.ImageField(upload_to='profile_pics/', verbose_name='الصورة الشخصية الإجبارية')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه من الإدارة')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العقار (مثال: شقة للبيع بالهضبة الوسطى)')),
                ('price', models.PositiveIntegerField(verbose_name='السعر (جنيه مصري)')),
                ('address', models.CharField(max_length=300, verbose_name='العنوان بالتفصيل (المقطم - الهضبة)')),
                ('description', models.TextField(verbose_name='الوصف التفصيلي للعقار')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='الصورة الرئيسية للعقار')),
                ('video', models.FileField(blank=True, null=True, upload_to='properties_videos/', validators=[core.models.validate_video_size], verbose_name='فيديو للعقار (اختياري - بحد أقصى 10MB)')),
                ('waiting_list', models.BooleanField(default=True, verbose_name='في قائمة الانتظار (غير معتمد)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('owner', models.ForeignKey(limit_choices_to={'account_type': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='صاحب العقار')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
