# Generated by Django 5.1.8 on 2026-06-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rejection_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الرفض من الإدارة'),
        ),
        migrations.AddField(
            model_name='property',
            name='rejection_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الرفض من الإدارة'),
        ),
    ]
